version: '3'
services:
  app:
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    command: python -u main.py
    tty: true
    stdin_open: true

  app2:
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    command: python -u main.py
    tty: true
    stdin_open: true

  app3:
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    command: python -u main.py
    tty: true
    stdin_open: true
    